# Generated by Django 6.0.7 on 2026-08-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termbaserate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termbaserate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
