# Generated by Django 6.0.7 on 2026-08-11 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_classroom_deleted_at_classroom_is_deleted_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='sessionreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('classroom', 'session_number'), name='unique_active_session_number_per_classroom'),
        ),
    ]
