# Generated by Django 6.0.7 on 2026-08-17 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_sessions_and_validations'),
        ('reports', '0002_alter_sessionreport_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='class_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='education.classsession'),
        ),
        migrations.AddConstraint(
            model_name='sessionreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('class_session',), name='unique_active_report_per_class_session'),
        ),
    ]
