# Generated by Django 6.0.7 on 2026-08-21 10:25

import config.project_clock
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_sessions_and_validations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionreport',
            name='submitted_at',
            field=models.DateTimeField(default=config.project_clock.project_now),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='updated_at',
            field=models.DateTimeField(default=config.project_clock.project_now),
        ),
    ]
