# Generated by Django 6.0.7 on 2026-08-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_classroom_deleted_at_classroom_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomWeekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_number', models.PositiveIntegerField()),
                ('session_date', models.DateField()),
            ],
            options={
                'ordering': ['session_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='unique_active_school_phone'),
        ),
        migrations.AddField(
            model_name='classroomweekday',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='education.classroom'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='education.classroom'),
        ),
        migrations.AddConstraint(
            model_name='classroomweekday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('classroom', 'weekday'), name='unique_active_weekday_per_classroom'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('classroom', 'session_number'), name='unique_active_class_session_number'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('classroom', 'session_date'), name='unique_active_class_session_date'),
        ),
    ]
